apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o84dw31fo-go 
  janus-idp.io/tekton: o84dw31fo-go
  backstage.io/kubernetes-id: o84dw31fo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o84dw31fo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  